
const PREFIX = 'midburn';

const SCREENS = {

  // tabs root
  CAMPS: `${PREFIX}.CAMPS`,
  PROGRAM: `${PREFIX}.PROGRAM`,
  MAP: `${PREFIX}.MAP`,
  ART: `${PREFIX}.ART`,
  NOW: `${PREFIX}.NOW`,
  EXTRA: `${PREFIX}.EXTRA`,
  
  PRINCIPLES: `${PREFIX}.PRINCIPLES`,
  
  // screens
  FILTER_TAGS: `${PREFIX}.FILTER_TAGS`,
  CAMP_SCREEN: `${PREFIX}.CAMP_SCREEN`,
  EVENT_DETAILS: `${PREFIX}.EVENT_DETAILS`,
  FAVOURITES: `${PREFIX}.FAVOURITES`,
  OPEN_SOURCES: `${PREFIX}.OPEN_SOURCES`,
};

export default SCREENS;